mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('<int:pk>/', views.Detalhe.as_view(), name='detalhe'),
    path('<int:pk>/resultados/', views.Resultados.as_view(), name='resultados'),
    path('<int:pergunta_id>/voto/', views.voto, name='voto'),
]

polls/models.py
import datetime

from django.contrib import admin
from django.db import models
from django.utils import timezone

class Pergunta(models.Model):
    texto_da_pergunta = models.CharField(max_length=200)
    data_da_publicacao = models.DateTimeField('data publicada')
    
    def __str__(self):
        return self.texto_da_pergunta
    
    @admin.display(
        boolean=True,
        ordering='data_da_publicacao',
        description='Publicado recentemente?',
    )
    
    def foi_publicado_recentemente(self):
        agora = timezone.now()
        return agora - datetime.timedelta(days=1) <= self.data_da_publicacao <= agora
    
class Alternativa(models.Model):
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    texto_da_alternativa = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)
    
    def __str__(self):
        return self.texto_da_alternativa

polls/views.py
from typing import Any
from django.db.models import F
from django.db.models.query import QuerySet
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Alternativa, Pergunta

class Index(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'lista_das_ultimas_perguntas'
    
    def get_queryset(self):
        return Pergunta.objects.filter(data_da_publicacao__lte=timezone.now()).order_by('-data_da_publicacao')[
            :5
        ]
    

class Detalhe(generic.DetailView):
    model = Pergunta
    template_name = 'polls/detalhe.html'
    
    def get_queryset(self):
        return Pergunta.objects.filter(data_da_publicacao__lte=timezone.now())
    


class Resultados(generic.DetailView):
    model = Pergunta
    template_name = 'polls/resultados.html'

def voto(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
    try:
        alternativa_selecionada = pergunta.alternativa_set.get(pk=request.POST['alternativa'])
    except (KeyError, Alternativa.DoesNotExist):
        return render(
            request,
            'polls/detalhe.html',
            {
                'pergunta': pergunta,
                'mensagem_de_erro': 'Você não selecionou uma alternativa',
            }
        )
    else:
        alternativa_selecionada.votos = F('votos') + 1
        alternativa_selecionada.save()
        return HttpResponseRedirect(reverse ('polls:resultados', args=(pergunta.id,)))

polls/templates/polls/detalhe.html
<form action='{% url 'polls:voto' pergunta.id %}' method='post'>
{% csrf_token %}
<fieldset>
    <legend><h2> {{ pergunta.texto_da_pergunta }}</h2></legend>
    {% if mensagem_de_erro %}<p><strong>{{ mensagem_de_erro }}</strong></p>{% endif %}
    {% for alternativa in pergunta.alternativa_set.all %}
        <input type='radio' name='alternativa' id='alternativa {{ forloop.counter }}' value='{{ alternativa.id }}'>
        <label for='alternativa {{ forloop.counter }}'>{{ alternativa.texto_da_alternativa }}</label><br>
    {% endfor %}
</fieldset>
<input type='submit' value='Voto'>
</form>

polls/templates/polls/index.html
{% load static %}

<link rel='stylesheet' href='{% static 'polls/style.css' %}'>

{% if lista_das_ultimas_perguntas %}
    <ul>
    {% for pergunta in lista_das_ultimas_perguntas %}
        <li><a href='{% url 'polls:detalhe' pergunta.id %}'>{{ pergunta.texto_da_pergunta }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Não há pergunta disponível.</p>
{% endif %}

polls/templates/polls/resultados.html
<h2>{{ pergunta.texto_da_pergunta }}</h2>

<ul>
{% for alternativa in pergunta.alternativa_set.all %}
    <li>{{ alternativa.texto_da_alternativa }} -- {{ alternativa.votos }} voto{{ alternativa.votos|pluralize }}</li>
{% endfor %}
</ul>

<a href='{% url 'polls:detalhe' pergunta.id %}'>Votar novamente</a><hr>
<a href='{% url 'polls:index' %}'> Retornar para tela inicial</a>